USE [Rozproszone_v1]
GO

INSERT INTO [dbo].[Department]
           ([Name], [IdCity])
     VALUES
			( 'Engineering', 1 ),
			( 'Marketing', 2 ),
			( 'Research and Development', 3 ),
			( 'Human Resources', 4 ),
			( 'Legal', 5 ),
			( 'Engineering', 6 ),
			( 'Training', 7 ),
			( 'Services', 8 ),
			( 'Accounting', 9 ),
			( 'Services', 10 ),
			( 'Product Management', 11 ),
			( 'Sales', 12 ),
			( 'Product Management', 13 ),
			( 'Research and Development', 14 ),
			( 'Services', 15 ),
			( 'Training', 16 ),
			( 'Services', 17 ),
			( 'Product Management', 18 ),
			( 'Services', 19 ),
			( 'Research and Development', 20 ),
			( 'Legal', 21 ),
			( 'Accounting', 22 ),
			( 'Legal', 23 ),
			( 'Research and Development', 24 ),
			( 'Legal', 25 ),
			( 'Sales', 26 ),
			( 'Services', 27 ),
			( 'Support', 28 ),
			( 'Services', 29 ),
			( 'Legal', 30 ),
			( 'Training', 31 ),
			( 'Research and Development', 32 ),
			( 'Services', 33 ),
			( 'Support', 34 ),
			( 'Training', 35 ),
			( 'Legal', 36 ),
			( 'Product Management', 37 ),
			( 'Sales', 38 ),
			( 'Marketing', 39 ),
			( 'Accounting', 40 ),
			( 'Accounting', 41 ),
			( 'Product Management', 1 ),
			( 'Support', 2 ),
			( 'Business Development', 3 ),
			( 'Product Management', 4 ),
			( 'Business Development', 5 ),
			( 'Sales', 6 ),
			( 'Accounting', 7 ),
			( 'Human Resources', 8 ),
			( 'Product Management', 9 ),
			( 'Marketing', 10 ),
			( 'Engineering', 11 ),
			( 'Business Development', 12 ),
			( 'Legal', 13 ),
			( 'Business Development', 14 ),
			( 'Training', 15 ),
			( 'Sales', 16 ),
			( 'Product Management', 17 ),
			( 'Training', 18 ),
			( 'Business Development', 19 ),
			( 'Product Management', 20 ),
			( 'Training', 21 ),
			( 'Research and Development', 22 ),
			( 'Marketing', 23 ),
			( 'Business Development', 24 ),
			( 'Product Management', 25 ),
			( 'Business Development', 26 ),
			( 'Sales', 27 ),
			( 'Engineering', 28 ),
			( 'Legal', 29 ),
			( 'Research and Development', 30 ),
			( 'Training', 31 ),
			( 'Services', 32 ),
			( 'Training', 33 ),
			( 'Business Development', 34 ),
			( 'Sales', 35 ),
			( 'Sales', 36 ),
			( 'Services', 37 ),
			( 'Product Management', 38 ),
			( 'Training', 39 ),
			( 'Accounting', 40 ),
			( 'Services', 41 ),
			( 'Product Management', 1 ),
			( 'Business Development', 2 ),
			( 'Accounting', 3 ),
			( 'Legal', 4 ),
			( 'Sales', 5 ),
			( 'Training', 6 ),
			( 'Marketing', 7 ),
			( 'Engineering', 8 ),
			( 'Research and Development', 9 ),
			( 'Accounting', 10 ),
			( 'Accounting', 11 ),
			( 'Legal', 12 ),
			( 'Research and Development', 13 ),
			( 'Support', 14 ),
			( 'Support', 15 ),
			( 'Services', 16 ),
			( 'Legal', 17 ),
			( 'Training', 18 ),
			( 'Engineering', 19 ),
			( 'Services', 20 ),
			( 'Research and Development', 21 ),
			( 'Human Resources', 22 ),
			( 'Marketing', 23 ),
			( 'Human Resources', 24 ),
			( 'Business Development', 25 ),
			( 'Services', 26 ),
			( 'Business Development', 27 ),
			( 'Research and Development', 28 ),
			( 'Human Resources', 29 ),
			( 'Services', 30 ),
			( 'Sales', 31 ),
			( 'Human Resources', 32 ),
			( 'Accounting', 33 ),
			( 'Accounting', 34 ),
			( 'Marketing', 35 ),
			( 'Support', 36 ),
			( 'Research and Development', 37 ),
			( 'Research and Development', 38 ),
			( 'Sales', 39 ),
			( 'Research and Development', 40 ),
			( 'Legal', 41 ),
			( 'Training', 1 ),
			( 'Human Resources', 2 ),
			( 'Human Resources', 3 ),
			( 'Human Resources', 4 ),
			( 'Legal', 5 ),
			( 'Legal', 6 ),
			( 'Engineering', 7 ),
			( 'Training', 8 ),
			( 'Services', 9 ),
			( 'Accounting', 10 ),
			( 'Business Development', 11 ),
			( 'Business Development', 12 ),
			( 'Marketing', 13 ),
			( 'Business Development', 14 ),
			( 'Product Management', 15 ),
			( 'Engineering', 16 ),
			( 'Sales', 17 ),
			( 'Sales', 18 ),
			( 'Marketing', 19 ),
			( 'Engineering', 20 ),
			( 'Support', 21 ),
			( 'Research and Development', 22 ),
			( 'Product Management', 23 ),
			( 'Accounting', 24 ),
			( 'Training', 25 ),
			( 'Engineering', 26 ),
			( 'Legal', 27 ),
			( 'Sales', 28 ),
			( 'Marketing', 29 ),
			( 'Services', 30 ),
			( 'Marketing', 31 ),
			( 'Human Resources', 32 ),
			( 'Accounting', 33 ),
			( 'Product Management', 34 ),
			( 'Support', 35 ),
			( 'Services', 36 ),
			( 'Services', 37 ),
			( 'Legal', 38 ),
			( 'Accounting', 39 ),
			( 'Accounting', 40 ),
			( 'Services', 41 ),
			( 'Business Development', 1 ),
			( 'Training', 2 ),
			( 'Research and Development', 3 ),
			( 'Human Resources', 4 ),
			( 'Legal', 5 ),
			( 'Support', 6 ),
			( 'Support', 7 ),
			( 'Legal', 8 ),
			( 'Product Management', 9 ),
			( 'Research and Development', 10 ),
			( 'Business Development', 11 ),
			( 'Business Development', 12 ),
			( 'Marketing', 13 ),
			( 'Sales', 14 ),
			( 'Research and Development', 15 ),
			( 'Support', 16 ),
			( 'Marketing', 17 ),
			( 'Services', 18 ),
			( 'Product Management', 19 ),
			( 'Marketing', 20 ),
			( 'Training', 21 ),
			( 'Services', 22 ),
			( 'Training', 23 ),
			( 'Support', 24 ),
			( 'Marketing', 25 ),
			( 'Engineering', 26 ),
			( 'Marketing', 27 ),
			( 'Accounting', 28 ),
			( 'Services', 29 ),
			( 'Business Development', 30 ),
			( 'Legal', 31 ),
			( 'Sales', 32 ),
			( 'Legal', 33 ),
			( 'Engineering', 34 ),
			( 'Business Development', 35 ),
			( 'Engineering', 36 ),
			( 'Marketing', 37 ),
			( 'Support', 38 ),
			( 'Research and Development', 39 ),
			( 'Product Management', 40 ),
			( 'Product Management', 41 ),
			( 'Accounting', 1 ),
			( 'Human Resources', 2 ),
			( 'Business Development', 3 ),
			( 'Human Resources', 4 ),
			( 'Human Resources', 5 ),
			( 'Engineering', 6 ),
			( 'Engineering', 7 ),
			( 'Sales', 8 ),
			( 'Human Resources', 9 ),
			( 'Training', 10 ),
			( 'Accounting', 11 ),
			( 'Marketing', 12 ),
			( 'Business Development', 13 ),
			( 'Legal', 14 ),
			( 'Human Resources', 15 ),
			( 'Sales', 16 ),
			( 'Engineering', 17 ),
			( 'Support', 18 ),
			( 'Marketing', 19 ),
			( 'Research and Development', 20 ),
			( 'Sales', 21 ),
			( 'Engineering', 22 ),
			( 'Support', 23 ),
			( 'Support', 24 ),
			( 'Support', 25 ),
			( 'Training', 26 ),
			( 'Sales', 27 ),
			( 'Research and Development', 28 ),
			( 'Sales', 29 ),
			( 'Accounting', 30 ),
			( 'Services', 31 ),
			( 'Legal', 32 ),
			( 'Services', 33 ),
			( 'Product Management', 34 ),
			( 'Research and Development', 35 ),
			( 'Engineering', 36 ),
			( 'Sales', 37 ),
			( 'Support', 38 ),
			( 'Marketing', 39 ),
			( 'Support', 40 ),
			( 'Research and Development', 41 ),
			( 'Marketing', 1 ),
			( 'Business Development', 2 ),
			( 'Human Resources', 3 ),
			( 'Support', 4 )

GO


